In [7]:
import numpy as np

In [75]:
class logisticregression:
    def __init__(self,n_iter=100,learn_rate=0.01):
        self.learn_rate=learn_rate
        self.n_iter=n_iter
        self.weight=None
        self.bias=None
    def fit(self,x,y):
        #init parameters    
        n_samples,n_features=x.shape
        #initialize a array of weights for every features with zero;so now X1*w1,X2*w2~~~X1*0,X2*0
        self.weight=np.zeros(n_features)
        #initialize the bias b=0
        self.bias=0
        #gradient descend 
        #runing for loop n_iter times 
        for _ in range(self.n_iter):
            #formulating y=xw+b
            linearModel=np.dot(x,self.weight)+self.bias
            #converting to sigmoid limiting range between 0 and 1
            y_pred=self._sigmoid(linearModel)
            #update weights
            dw=(1/n_samples)*np.dot(x.T,(y_pred-y))
            db=(1/n_samples)*np.sum(y_pred-y)
            self.weight-=self.learn_rate*dw
            self.bias-=self.learn_rate*db
            
            
            
        
    def predict(self,x):
        #formulating y=xw+b
        linearModel=np.dot(x,self.weightight)+bias
        #converting to sigmoid limiting range between 0 and 1
        y_pred=self._sigmoid(linearModel)
        
        ypred_class=[1 if i>0.5 else 0 for i in y_pred]
        
        return ypred_class
        
    def _sigmoid(self,x):
        return 1/1+np.exp(-x)

In [76]:
import pandas as pd

In [77]:
data=pd.read_csv("heart.csv")

In [78]:
X=data.iloc[:,:-1] 
X

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [79]:
y=data.iloc[:,-1]
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [80]:
from sklearn.model_selection import train_test_split

In [81]:
X_train,X_test,y_train,y_test=train_test_split(X,y)

In [82]:
regressor=logisticregression()

In [83]:
regressor.fit(X,y)

C:\Users\PARTHA\AppData\Local\Programs\Python\Python36\lib\site-packages\ipykernel_launcher.py:41: RuntimeWarning: overflow encountered in exp